## Target Guided Ordinal Encoding
It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [1]:
import pandas as pd

# create a sample dataframe with a categorical variable and a target variable
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [ ]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [2]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [3]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [4]:
df['city_encoded']=df['city'].map(mean_price)

In [6]:
df[['price','city','city_encoded']]

   price      city  city_encoded
0    200  New York         190.0
1    150    London         150.0
2    300     Paris         310.0
3    250     Tokyo         250.0
4    180  New York         190.0
5    320     Paris         310.0

In [10]:
import seaborn as sns
tip = sns.load_dataset('tips')

In [14]:
mean_bill = tip.groupby('time')['total_bill'].mean().to_dict()

/tmp/ipykernel_2457/3683797411.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_bill = tip.groupby('time')['total_bill'].mean().to_dict()

In [15]:
mean_bill

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [16]:
tip['time_encoded'] = tip['time'].map(mean_bill)

In [17]:
tip[['time_encoded','time','total_bill']]

    time_encoded    time  total_bill
0      20.797159  Dinner       16.99
1      20.797159  Dinner       10.34
2      20.797159  Dinner       21.01
3      20.797159  Dinner       23.68
4      20.797159  Dinner       24.59
..           ...     ...         ...
239    20.797159  Dinner       29.03
240    20.797159  Dinner       27.18
241    20.797159  Dinner       22.67
242    20.797159  Dinner       17.82
243    20.797159  Dinner       18.78

[244 rows x 3 columns]